// Code generated by Kitex v0.10.1. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	v1 "go-cloud-storage/pb/kitex_gen/api/v1"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Signup(ctx context.Context, Req *v1.SignupRequest, callOptions ...callopt.Option) (r *v1.SignupResponse, err error)
	Login(ctx context.Context, Req *v1.LoginRequest, callOptions ...callopt.Option) (r *v1.LoginResponse, err error)
}

// NewClient creates a client for the app defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the app defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Signup(ctx context.Context, Req *v1.SignupRequest, callOptions ...callopt.Option) (r *v1.SignupResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Signup(ctx, Req)
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *v1.LoginRequest, callOptions ...callopt.Option) (r *v1.LoginResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}
