// Code generated by Kitex v0.10.1. DO NOT EDIT.
package userservice

import (
	server "github.com/cloudwego/kitex/server"
	v1 "go-cloud-storage/pb/kitex_gen/api/v1"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v1.UserService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler v1.UserService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
